### ISSUE TITLE
findDomNode is deprecated in latest React version (StrictMode)

### ISSUE THREAD

**Issue by JeffML** [yo35/kokopu-react#2]
Looks like the culprit is DraggableCore

![Screenshot 2022-12-05 11 52 15 AM](https://user-images.githubusercontent.com/3497069/205730585-a7fdd4bc-5ed8-423b-8136-75c5d39d22e8.png)

**Comment by yo35** [comment]
Fixed in 1.9.2, following the recommandation in https://github.com/react-grid-layout/react-draggable/issues/685

Thanks for reporting the issue.
