### ISSUE TITLE
Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by mayur-samrutwar** [yo35/kokopu-react#4]
```
./node_modules/kokopu-react/dist/lib/chessboard/Chessboard.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\kokopu-react\dist\lib\chessboard\ChessboardImpl.js
```

This error is coming after importing Chessboard comp.

**Comment by yo35** [comment]
The NextJs policy regarding how CSS imports from within node_modes has been debated here:
https://github.com/vercel/next.js/issues/19936

From what I understand of the discussion, this policy has been changed in NextJs 13.

Anyway, this is not a bug of Kokopu-React.
