### ISSUE TITLE
symbols.css is showing up as half a MB

### ISSUE THREAD

**Issue by JeffML** [yo35/kokopu-react#5]
It's the largest dependency in my project right now.

![image](https://github.com/yo35/kokopu-react/assets/3497069/c1a7521e-5323-436b-843e-69f9830d8f46)

After a webpack build, the CSS is huge, but the CSS source file is only 2K, so I wonder what's going on?  Any idea?

**Comment by JeffML** [comment]
I upgraded my packages (kokopu-react v3.0.1), and now I show piecesets.ts as being 530KB.  After doing some research, I believe webpack  is converting the image links in that file to byte-encoded images (in addition to packing up the now-redundant sprite png files). 

I'm not sure what to recommend.  Perhaps make piece sets separate packages from kokopu-react proper?

**Comment by yo35** [comment]
What Webpack does depends on how you configure it. For example, if you look at the source code of the lib documentation (https://kokopu-react.yo35.org/docs/3.0.1/build/bundle.2948829d.js) - which contains a webpacked-version of the lib itself - you'll see that the chess piece images are referenced by their URL, as expected.

**Comment by JeffML** [comment]
Yes, but in this case I used create-react-app to initialize my react
project, which was pretty standard at the time. Unfortunately it
encapsulates webpack in a way that's not configurable (which is one reason
why it recently became no longer the standard).

So I will have to fork something. I only need one piece set (which is
probably the most common use case), so I will look at forking kokopu-react
and strip out the sets I don't need.

**Comment by JeffML** [comment]
Or maybe I misunderstood... I can use the already bundled version instead?
I'll try that.

**Comment by yo35** [comment]
create-react-app offers several options to customize its behavior. In particular, whether images should be inlined or not is controlled by the `IMAGE_INLINE_SIZE_LIMIT` environment variable. See create-react-app documentation:
https://create-react-app.dev/docs/adding-images-fonts-and-files

**Comment by JeffML** [comment]
Okay, thank you for that bit of information. I did research this and it
seems to be unknown to many (I also looked at the react-scripts code, and
saw a 10000Mb limit hardcoded somewhere, but perhaps that's overridden
elsewhere).

I'll give it a try.

**Comment by JeffML** [comment]
10000 bytes, not Mb  <:-\

Okay, that seems to work and thanks again. Now I have to go to all the message boards I checked and inform them of this env var and be a hero. Closing.
