### ISSUE TITLE
FEATURE REQUEST: add moveList and moveTo parameters to Chessboard

### ISSUE THREAD

**Issue by JeffML** [yo35/kokopu-react#6]
In addition, add forward/back controls to the Chessboard diagram if a move list is provided (instead of a position object). Currently, I have to maintain and manage moves in a separate object, then extract a FEN and redraw Chessboard.

**Comment by yo35** [comment]
Version 3.1.0 adds [`NavigationBoard`](https://kokopu-react.yo35.org/docs/current/#/Components/NavigationBoard), i.e. a component representing a chessboard + forward/backward buttons to navigate within the positions of a [`Game`](https://kokopu.yo35.org/docs/current/classes/Game.html) object.
